apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue 
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue-pod
        image: manojpadigineti/nginx:blue
        ports:
        - protocol: TCP
          containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: blue-service
spec:
  type: ClusterIP
  selector:
    app: blue
  ports:
  - name:  http 
    port:  80
    protocol: TCP

---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: path 
  annotations: kubernetes.io/ingress.class: "gce"
spec:
  rules:
   - http: 
       paths: 
       - pathType: prefix
         path: "/blue"
         backend:
           service: 
             name: blue-service
             port:
               number: 80 

       